### ISSUE TITLE
pyproject.toml file in the pypi package

### ISSUE THREAD

**Issue by Mrngilles** [EVasseure/cprint#7]
I had an issue installing the package, and after downloading the `.tar.gz` from PyPi, I noticed that there were a `pyproject.toml` that is not in the repository.

For a reason unknown, it prevents installation on my side when installing in an environment generated using pipenv:

```
pipenv run pip install cprint
```

```
Collecting cprint
  Downloading cprint-1.2.1.tar.gz (2.5 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
ERROR: Requested cprint from https://files.pythonhosted.org/packages/b4/7b/5fac29831c77a9ccdfd4d3dfec9e142a977e1c6bf6167f50beaa3220a04d/cprint-1.2.1.tar.gz#sha256=a8ebbae938b5481b51298e6b5473795a0af2d309a30e4b5d83b692ec9abbe20b has different version in metadata: '0.1.0'
```

When installing out of the environment, it did work by getting the previous version:

```
pip install cprint
```

```
Collecting cprint
  Using cached cprint-1.2.1.tar.gz (2.5 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
WARNING: Discarding https://files.pythonhosted.org/packages/b4/7b/5fac29831c77a9ccdfd4d3dfec9e142a977e1c6bf6167f50beaa3220a04d/cprint-1.2.1.tar.gz#sha256=a8ebbae938b5481b51298e6b5473795a0af2d309a30e4b5d83b692ec9abbe20b (from https://pypi.org/simple/cprint/). Requested cprint from https://files.pythonhosted.org/packages/b4/7b/5fac29831c77a9ccdfd4d3dfec9e142a977e1c6bf6167f50beaa3220a04d/cprint-1.2.1.tar.gz#sha256=a8ebbae938b5481b51298e6b5473795a0af2d309a30e4b5d83b692ec9abbe20b has inconsistent version: filename has '1.2.1', but metadata has '0.1.0'
  Downloading cprint-1.2.tar.gz (1.4 kB)
Using legacy 'setup.py install' for cprint, since package 'wheel' is not installed.
Installing collected packages: cprint
    Running setup.py install for cprint ... done
Successfully installed cprint-1.2
```

Here are the contents of the `pyproject.toml` file:

```toml
[tool.poetry]
name = "cprint"
version = "0.1.0"
description = ""
authors = ["Erwan <erwan@kowffice.com>"]

[tool.poetry.dependencies]
python = "^3.8"
tox = "^3.21.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

Installing in pipenv by setting the version to `==1.2` does work without any issue.
